id: P001674
initial_creation_type: ocr
source_metadata:
  id: bdr:W30056
  title: བོད་ཀྱི་ཤེས་རིག་གི་མདུན་ལམ་གླེང་བའི་འབོལ་རྩོམ།
  author: ''
  volumes:
    4be8523c86f8433d989734afb719d02a:
      image_group_id: I1KG12368
      title: ''
      volume_number: 1
      total_pages: 194
      base_file: v001.txt
