id: IBE0D7936
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T12:55:22+00:00'
last_modified: '2022-06-07T13:59:31.842544+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30056
  title: བོད་ཀྱི་ཤེས་རིག་གི་མདུན་ལམ་གླེང་བའི་འབོལ་རྩོམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '9049':
      image_group_id: I1KG12368
      title: ''
      total_pages: 194
      order: 1
      base_file: 9049.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
